import {setupMephistoWeb} from './mephisto-web.js';
import {positionBody,coachBody,speechBody,answer,geminiBody,geminiCoachBody,geminiAnswer} from './browser-api.js';
// Local browser bridge. No keys or game data are sent to the local file server.
let callback,provider=localStorage.getItem('sprachschach-browser-provider')||'tts',enabled=false,lang='de-DE',busy=false,picker=false,speaking=false,waiting=false,recognition=null,audio=null,speechId=0,restart;
const emit=(name,...args)=>callback?.(name,args),state=s=>emit('voiceState',s),note=(de,en=de)=>emit('notice',de,en);
const request=(r)=>new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
const db=()=>new Promise((resolve,reject)=>{const r=indexedDB.open('sprachschach-browser-keys',1);r.onupgradeneeded=()=>r.result.createObjectStore('keys');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
async function storeRead(name){const d=await db();try{return await request(d.transaction('keys').objectStore('keys').get(name));}finally{d.close();}}
async function storeWrite(name,value){const d=await db();try{await new Promise((resolve,reject)=>{const t=d.transaction('keys','readwrite');const s=t.objectStore('keys');value===null?s.delete(name):s.put(value,name);t.oncomplete=resolve;t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error);});}finally{d.close();}}
async function encryptionKey(){let k=await storeRead('aes');if(!k){k=await crypto.subtle.generateKey({name:'AES-GCM',length:256},false,['encrypt','decrypt']);await storeWrite('aes',k);}return k;}
async function readKey(kind){const entry=await storeRead(kind);if(!entry)return '';return new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:entry.iv},await encryptionKey(),entry.data));}
async function saveKey(value,selection,kind='openai'){if(typeof value!=='string'||value.trim().length<15)return {ok:false,error:'invalid_key'};try{const iv=crypto.getRandomValues(new Uint8Array(12)),data=await crypto.subtle.encrypt({name:'AES-GCM',iv},await encryptionKey(),new TextEncoder().encode(value.trim()));await storeWrite(kind,{iv,data});if(kind!=='google')setProvider(selection);return {ok:true};}catch{return {ok:false,error:'encryption_unavailable'};}}
async function api(kind,path,body,timeout=85000){const key=await readKey(kind);if(!key)throw Error('Kein API-Schlüssel eingerichtet.');const google=kind==='google',url=google?'https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent':'https://api.openai.com/v1/'+path;const response=await fetch(url,{method:'POST',headers:google?{'x-goog-api-key':key,'Content-Type':'application/json'}:{Authorization:'Bearer '+key,'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(timeout)});if(!response.ok)throw Error('API-Fehler '+response.status);return response;}
function resume(){clearTimeout(restart);if(enabled&&!busy&&!picker&&!speaking&&!waiting&&!document.hidden)restart=setTimeout(()=>listen(lang),500);}
function halt(){clearTimeout(restart);if(recognition){recognition.onend=null;recognition.abort();recognition=null;}}
function listen(language){if(busy||picker||speaking||document.hidden)return;if(!window.pwaSpeechStarted){state('off');return;}halt();lang=language;const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){state('unavailable');note('Dieser Browser bietet keine Spracherkennung. Bitte Siri/Diktieren und Mikrofonzugriff in Safari prüfen; alternativ Züge eintippen.');return;}const r=recognition=new R();r.lang=language;r.continuous=false;r.interimResults=false;r.onstart=()=>state('listening');r.onresult=e=>{waiting=true;state('recognizing');emit('receiveSpeech',[e.results[0][0].transcript]);};r.onerror=e=>{if(e.error==='not-allowed'||e.error==='service-not-allowed'){enabled=false;state('permission_denied');}else if(e.error!=='aborted'){state('unavailable');}};r.onend=()=>{if(recognition===r)recognition=null;resume();};try{r.start();}catch{state('unavailable');}}
function stop(){speechId++;speaking=false;waiting=false;halt();speechSynthesis.cancel();if(audio){audio.pause();audio=null;}emit('stopAudio');resume();}
function localSpeak(text,language,id){const u=new SpeechSynthesisUtterance(text);u.lang=language;const voices=speechSynthesis.getVoices();u.voice=voices.find(v=>v.lang===language&&/Google|Microsoft/.test(v.name))||voices.find(v=>v.lang.startsWith(language.slice(0,2)))||null;u.onend=u.onerror=()=>{if(id!==speechId)return;speaking=false;state('ready');resume();};speechSynthesis.speak(u);}
async function speak(text,language){stop();halt();speaking=true;state('speaking');const id=++speechId;if(provider==='openai'){try{const response=await api('openai','audio/speech',speechBody(text,language),45000);if(id!==speechId)return;const bytes=new Uint8Array(await response.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));emit('playAudio',id,btoa(binary));return;}catch{note('OpenAI-Sprachausgabe nicht verfügbar; die Browser-Stimme liest vor.');}}if(id===speechId)localSpeak(text,language,id);}
function setProvider(value){provider=value==='openai'?'openai':'tts';localStorage.setItem('sprachschach-browser-provider',provider);emit('voiceEngineChanged',provider==='openai');}
function download(data,name,type){const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function choose(accept,handler){picker=true;halt();const input=document.createElement('input');input.type='file';input.accept=accept;input.oncancel=()=>{picker=false;resume();};input.onchange=async()=>{try{if(input.files[0])await handler(input.files[0]);}catch{note('Die Datei konnte nicht gelesen werden.');}finally{picker=false;resume();}};input.click();}
async function imageFile(file){if(file.size>16*1024*1024)throw Error();const bitmap=await createImageBitmap(file),s=Math.min(1,2048/Math.max(bitmap.width,bitmap.height)),c=document.createElement('canvas');c.width=Math.round(bitmap.width*s);c.height=Math.round(bitmap.height*s);c.getContext('2d').drawImage(bitmap,0,0,c.width,c.height);bitmap.close();return c.toDataURL('image/jpeg',.94);}
window.Android={speak,stop,listen,configureChat:selected=>{picker=true;halt();emit('configureKey',selected==='gemini'?'google':'openai',true);},setHandsFree:(on,language)=>{enabled=!!on;lang=language;if(on)resume();else{halt();state('off');}},inputFinished:()=>{waiting=false;resume();},setVoiceBusy:on=>{busy=!!on;if(busy)halt();else resume();},configureOpenAI:()=>{picker=true;halt();emit('configureKey','openai');},configureGemini:()=>{picker=true;halt();emit('configureKey','google');},setSpeechProvider:setProvider,askCoach:async(id,payload)=>{try{const google=JSON.parse(payload).provider==='gemini',r=await api(google?'google':'openai','responses',google?geminiCoachBody(payload):coachBody(payload));emit('coachAnswer',id,google?geminiAnswer(await r.json()):answer(await r.json()),'');}catch{emit('coachAnswer',id,'','API nicht erreichbar; lokale Erklärung verwendet.');}},pickPositionPhoto:camera=>{if(camera){picker=true;halt();emit('camera');}else choose('image/*',async f=>emit('photoSelected',await imageFile(f),''));},recognizePositionPhoto:async(id,image,orientation,language,model)=>{try{const google=model==='gemini-flash-latest',r=await api(google?'google':'openai','responses',google?geminiBody(image,orientation,language):positionBody(image,orientation,language,model),model==='gpt-6.1-sol'?145000:85000),data=await r.json();emit('photoRecognized',id,google?geminiAnswer(data):answer(data),'');}catch(e){emit('photoRecognized',id,'',e.message||'API nicht erreichbar.');}},pickChessDocument:()=>choose('.pgn,.fen,.txt',async f=>{if(f.size>1024*1024)throw Error();emit('receiveSharedContent',String(Date.now()),'text',await f.text());}),copyPgn:async pgn=>{try{await navigator.clipboard.writeText(pgn);note('PGN in die Zwischenablage kopiert.');}catch{note('Zwischenablage nicht verfügbar. Bitte PGN speichern.');}},savePgn:(pgn,name)=>download(pgn,name,'application/x-chess-pgn'),sharePgn:async(pgn,name)=>{const file=new File([pgn],name,{type:'application/x-chess-pgn'});if(navigator.canShare?.({files:[file]})){try{await navigator.share({files:[file]});}catch(e){if(e.name!=='AbortError')download(pgn,name,'application/x-chess-pgn');}}else download(pgn,name,'application/x-chess-pgn');},finishIncoming:()=>{},setLcdFullscreen:on=>{if(on)document.documentElement.requestFullscreen?.().catch(()=>{});else if(document.fullscreenElement)document.exitFullscreen?.().catch(()=>{});}};
window.desktopHost={onEvent:fn=>callback=fn,ready:()=>{setProvider(provider);resume();},keyStatus:async(kind='openai')=>({hasKey:!!(await readKey(kind)),provider}),saveKey,forgetKey:async(kind='openai')=>{await storeWrite(kind,null);if(kind==='openai')setProvider('tts');},pickerBusy:on=>{picker=on;if(on)halt();else resume();},capture:data=>emit('photoSelected',data,''),audioFinished:id=>{if(id===speechId){speaking=false;resume();}},audioFallback:id=>{if(id===speechId){speaking=false;state('unavailable');resume();}},showArchiveBackup:()=>emit('exportArchive'),exportArchive:data=>download(data,'SprachSchach-Partien-und-Chat.json','application/json'),importArchive:()=>choose('.json',async f=>{if(f.size>32*1024*1024)throw Error();emit('restoreArchive',await f.text());})};
document.addEventListener('visibilitychange',()=>{if(document.hidden){halt();state('paused');}else resume();emit('engineForegroundChanged',!document.hidden);});

setupMephistoWeb();
