import {Chess,parseMove,explain,names} from './core.js';
import {moveObject,uci,terminalEvaluation,resultText} from './review.js';
export function speechIntent(text){const s=text.toLowerCase().trim();
 if(/^(?:ich gebe auf|aufgeben|partie aufgeben|i resign|resign)[.! ]*$/.test(s))return 'resign';
 if(/^(?:remis anbieten|remis vereinbaren|offer draw|offer a draw|agree draw)[.! ]*$/.test(s))return 'draw_offer';
 if(/^(?:neue variante|variante ab hier|variante anlegen|start variation|new variation)[.! ]*$/.test(s))return 'variant_new';
 if(/^(?:hauptvariante|zur hauptvariante|main line|return to main line)[.! ]*$/.test(s))return 'variant_main';
 if(/^(?:bitte |please )?(?:stellung fotografieren|stellung erkennen|schachstellung erkennen|stellung einlesen|(?:erkenne|fotografiere|scanne) (?:die stellung|das (?:schach)?brett)|(?:schach)?brett fotografieren|brett scannen|schachbrett scannen|foto aufnehmen|scan (?:the )?board|scan position|recognize (?:the )?position|take (?:a )?photo)[.! ]*$/.test(s))return 'camera';
 if(/^(?:bitte |please )?(?:screenshot laden|bild laden|bild hochladen|screenshot hochladen|load (?:an )?image|load screenshot)[.! ]*$/.test(s))return 'image';
 if(/^(?:bitte |please )?(?:pgn importieren|fen importieren|partie importieren|import pgn|import fen|import game)[.! ]*$/.test(s))return 'import';
 if(/^(?:nächster zug|naechster zug|next move)[.! ]*$/.test(s))return 'replay_next';
 if(/^(?:vorheriger zug|previous move)[.! ]*$/.test(s))return 'replay_prev';
 if(/^(?:ans ende|partieende zeigen|go to end)[.! ]*$/.test(s))return 'replay_end';
 if(/^(?:zum anfang|anfangsstellung zeigen|go to start)[.! ]*$/.test(s))return 'replay_start';
 if(/^(?:bitte |please )?(?:freisprechen (?:aus|pausieren)|mikrofon aus|nicht mehr zuhören|stop listening|pause listening|hands.?free off)[.! ]*$/.test(s))return 'pause';
 if(/^(?:bitte |please )?(?:wiederholen|wiederhole(?: das)?|noch einmal(?: vorlesen)?|repeat(?: that)?|read again)[.! ]*$/.test(s))return 'repeat';
 if(/^(?:bitte |please )?(?:zug zurück|zurücknehmen|letzten zug zurück|undo(?: move)?|take back(?: the last move)?)[.! ]*$/.test(s))return 'undo';
 if(/^(?:bitte |please )?(?:neue partie|new game)[.! ]*$/.test(s))return 'new';
 if(/^(?:bitte |please )?(?:pgn kopieren|partie kopieren|copy pgn|copy game)[.! ]*$/.test(s))return 'copy';
 if(/^(?:bitte |please )?(?:pgn teilen|partie teilen|share pgn|share game)[.! ]*$/.test(s))return 'share';
 if(/^(?:bitte |please )?(?:pgn speichern|save pgn)[.! ]*$/.test(s))return 'save';
 if(/[?]|\b(bewerte|bewertung|analysiere|analyse|einschätzung|evaluate|evaluation|assess|analyze|assessment|warum|wieso|weshalb|erklär|erkläre|erklären|was|wie|welche|welcher|welches|soll|sollte|kann ich|könnte|guter zug|schlechter zug|tipp|hilfe|hallo|danke|why|explain|what|how|which|should|could|can i|hint|help|hello|thanks|good move|bad move|recommend)\b/.test(s))return 'question';
 return 'move';
}
const fromUci=s=>({from:s.slice(0,2),to:s.slice(2,4),...(s[4]?{promotion:s[4]}:{})});
export async function localDialogue(game,question,lang,analyze,previous=null,startFen=undefined){const de=lang==='de',say=(a,b)=>de?a:b,s=question.toLowerCase(),prefix=game.history({verbose:true}).map(uci);const context={board_fen:game.fen(),side_to_move:game.turn(),legal_moves:game.moves(),question};
 const concepts=[[/rochade|castling/,['Bei der Rochade zieht der König zwei Felder zum Turm; der Turm springt auf die andere Seite des Königs. König und Turm dürfen zuvor nicht gezogen haben. Der König darf nicht im Schach stehen oder über ein angegriffenes Feld ziehen.','Castling moves the king two squares towards the rook; the rook moves to the other side of the king. Neither may have moved before. The king must not be in check or pass through an attacked square.']], [/en passant/,['En passant kann ein Bauer einen gegnerischen Bauern schlagen, der gerade zwei Felder vorgerückt ist. Das ist nur unmittelbar im nächsten Zug möglich.','En passant lets a pawn capture an opposing pawn that has just advanced two squares. It is only available on the very next move.']], [/patt|stalemate/,['Patt bedeutet: Die Seite am Zug hat keinen legalen Zug, steht aber nicht im Schach. Die Partie endet remis.','Stalemate means the side to move has no legal move but is not in check. The game is drawn.']], [/gabel|fork/,['Eine Gabel greift mit einer Figur gleichzeitig mehrere gegnerische Figuren an. Springer eignen sich dafür besonders gut. Ob eine Gabel hier möglich ist, muss an den legalen Zügen geprüft werden.','A fork attacks several opposing pieces at once with one piece. Knights are particularly suited to this. Whether a fork is available here depends on the legal moves.']], [/zentrum|center|centre/,['Die zentralen Felder d4, e4, d5 und e5 sind wichtig, weil Figuren von dort häufig mehr Möglichkeiten haben. Zentrale Bauern und entwickelte Figuren helfen, diese Felder zu kontrollieren.','The central squares d4, e4, d5 and e5 matter because pieces often have more options there. Central pawns and developed pieces help control them.']]];
 if(/hallo|hello|danke|thanks/.test(s))return {text:say('Gern. Du kannst einen Zug ansagen, nach einem Tipp fragen oder sagen: Warum war der letzte Zug gut?','Happy to help. You can speak a move, ask for a hint, or say: Why was the last move good?'),context};
 for(const [pattern,answers]of concepts)if(pattern.test(s))return {text:answers[de?0:1],context};
 if(/zusammenfassung|summary/.test(s))return {text:say('Die Zusammenfassung findest du am Ende der Partie. Dort werden gute Züge und Patzer mit Diagrammen erläutert.','The summary appears at the end of the game, with diagrams of good moves and blunders.'),context};
 if(/bewert|analys|einschätzung|evaluat|assess|analy[sz]|wie.*stellung|how.*position/.test(s)){
  const terminal=terminalEvaluation(game),result=terminal?{evaluation:terminal}:await analyze(prefix,game.turn()),evaluation=result.evaluation;if(!evaluation)throw new Error('Missing evaluation');context.evaluation=evaluation;
  if(game.isGameOver())return {text:resultText(game,lang),context};
  let text;if(evaluation.mate!==undefined){const side=evaluation.mate>0?say('Weiß','White'):say('Schwarz','Black');text=say(`Stockfish sieht einen erzwungenen Mattangriff für ${side}, Matt in ${Math.abs(evaluation.mate)} Zügen.`,`Stockfish sees a forced mating attack for ${side}, mate in ${Math.abs(evaluation.mate)} moves.`);}else{const value=evaluation.cp/100,advantage=value>0?say('Vorteil für Weiß','an advantage for White'):value<0?say('Vorteil für Schwarz','an advantage for Black'):say('ausgeglichen','equal');text=say(`Die kurze Stockfish-Analyse bewertet die Stellung mit ${value>0?'+':''}${value.toFixed(2)} Bauerneinheiten aus Sicht von Weiß: ${advantage}.`,`The short Stockfish analysis evaluates the position at ${value>0?'+':''}${value.toFixed(2)} pawn units from White’s perspective: ${advantage}.`);}
  if(/^[a-h][1-8][a-h][1-8][qrbn]?$/.test(result.move||'')){const copy=new Chess(game.fen()),move=copy.move(fromUci(result.move));context.recommended_uci=result.move;context.recommended_san=move.san;text+=' '+say(`Stockfish empfiehlt ${names.de[move.piece]} von ${move.from} nach ${move.to}, also ${move.san}.`,`Stockfish recommends ${names.en[move.piece]} from ${move.from} to ${move.to}, ${move.san}.`);}
  return {text,context};
 }
 const hint=/tipp|hilfe|soll|hint|recommend|what.*(?:play|move)|best move/.test(s);
 if(hint&&!game.isGameOver()){const result=await analyze(prefix,game.turn());const m=result.move;if(!/^[a-h][1-8][a-h][1-8][qrbn]?$/.test(m))throw new Error('No recommendation');const copy=new Chess(game.fen()),played=copy.move(fromUci(m));context.recommended_uci=m;context.recommended_san=played.san;context.evaluation=result.evaluation;return {text:say(`Stockfish empfiehlt ${names.de[played.piece]} von ${played.from} nach ${played.to}, also ${played.san}. ${explain(played,copy,lang)} Das ist eine kurze Analyse, keine endgültige Bewertung.`,`Stockfish recommends ${names.en[played.piece]} from ${played.from} to ${played.to}, ${played.san}. ${explain(played,copy,lang)} This is a short analysis, not a definitive assessment.`),context};}
 let candidates=parseMove(game,question),candidate=candidates.length===1?candidates[0]:null;
 if(!candidate&&previous?.board_fen===game.fen()&&previous.recommended_uci&&/warum|why|dies|that|gut|good/.test(s)){const proposed=fromUci(previous.recommended_uci);candidate=game.moves({verbose:true}).find(m=>uci(m)===uci(proposed));}
 let before,after,played,beforePrefix,afterPrefix;
 if(candidate){before=new Chess(game.fen());after=new Chess(game.fen());played=after.move(moveObject(candidate));beforePrefix=prefix;afterPrefix=[...prefix,uci(played)];}
 else{const history=game.history({verbose:true});if(!history.length)return {text:say('Es wurde noch kein Zug gespielt. Sage zum Beispiel „e zwei nach e vier“ oder frage nach einem Tipp.','No move has been played yet. Try “e two to e four”, or ask for a hint.'),context};before=new Chess(startFen);for(const m of history.slice(0,-1))before.move(moveObject(m));after=game;played=history.at(-1);beforePrefix=prefix.slice(0,-1);afterPrefix=prefix;}
 const first=terminalEvaluation(before)|| (await analyze(beforePrefix,before.turn())).evaluation;const second=terminalEvaluation(after)|| (await analyze(afterPrefix,after.turn())).evaluation;if(!first||!second)throw new Error('Missing evaluation');const loss=Math.max(0,(first.cp-second.cp)*(played.color==='w'?1:-1));context.explained_move=uci(played);context.before=first;context.after=second;context.loss_cp=loss;
 let assessment=after.isCheckmate()?resultText(after,lang):loss>=200?say(`Stockfish sieht etwa ${(loss/100).toFixed(1)} Bauerneinheiten Bewertungsverlust: ein möglicher Patzer.`,`Stockfish estimates an evaluation loss of about ${(loss/100).toFixed(1)} pawn units: a possible blunder.`):loss>=80?say('Die kurze Stockfish-Analyse sieht einen möglichen Fehler.','The short Stockfish analysis indicates a possible mistake.'):say('Nach der kurzen Stockfish-Analyse hält dieser Zug die Bewertung weitgehend.','According to the short Stockfish analysis, this move largely preserves the evaluation.');
 if(second.mate!==undefined&&second.cp*(played.color==='w'?1:-1)<0)assessment=say('Stockfish sieht danach einen erzwungenen Mattangriff des Gegners.','Stockfish sees a forced mating attack for the opponent afterwards.');
 return {text:(candidate?say('Zu deinem Zugvorschlag: ','About your suggested move: '):say('Zum angesprochenen Zug: ','About the move you asked about: '))+explain(played,after,lang)+' '+assessment,context};
}
