/* iPad renderer adaptation; the chess application itself is shared unchanged. */
const host=window.desktopHost;
const de=()=>document.querySelector('#language')?.value!=='en';
const text=(german,english)=>de()?german:english;
let audio=null,audioUrl=null,stream=null,cameraDialog=null,keyDialog=null;
function setText(selector,value){const n=document.querySelector(selector);if(n&&n.textContent!==value)n.textContent=value;}
function labels(){
 document.body.classList.add('desktop');
 setText('#speechProvider option[value="tts"]',text('iPad-Stimme · kostenlos','iPad voice · free'));
 setText('#speechProviderHelp',text('Safari-Spracherkennung und iPad-Stimme sind kostenlos. OpenAI nutzt deinen gespeicherten API-Schlüssel und wird separat berechnet.','iPad recognition and iPad voice are free. OpenAI uses your stored API key and is billed separately.'));
 const status=document.querySelector('#voiceStatus');if(status?.textContent.includes('Android'))status.textContent=status.textContent.replace('Android-Stimme','iPad-Stimme').replace('Android voice','iPad voice');
 const privacy=document.querySelector('#privacy');if(privacy?.textContent.includes('Android'))privacy.textContent=privacy.textContent.replaceAll('Android','iPad');
}
function notice(german,english){const n=document.querySelector('#message');if(n)n.textContent=text(german,english);}
function stopAudio(){if(audio){audio.pause();audio.src='';audio=null;}if(audioUrl){URL.revokeObjectURL(audioUrl);audioUrl=null;}}
async function playAudio(id,base64){stopAudio();const bytes=Uint8Array.from(atob(base64),c=>c.charCodeAt(0));audioUrl=URL.createObjectURL(new Blob([bytes],{type:'audio/mpeg'}));audio=new Audio(audioUrl);audio.onended=()=>{stopAudio();host.audioFinished(id);};audio.onerror=()=>{stopAudio();host.audioFallback(id);};try{await audio.play();}catch{stopAudio();host.audioFallback(id);}}
async function configureKey(kind='openai',keepSpeech=false){const google=kind==='google';if(keyDialog?.open){host.pickerBusy(false);return;}const status=await host.keyStatus(kind);keyDialog=document.createElement('dialog');keyDialog.className='desktop-dialog';keyDialog.innerHTML=`<h2>${google?text('Gemini einrichten','Configure Gemini'):text('OpenAI einrichten','Configure OpenAI')}</h2><p>${google?text('Ein eigener Google-API-Schlüssel wird einmalig mit AES-GCM im lokalen Safari-Profil verschlüsselt gespeichert. Kosten bzw. kostenloses Kontingent hängen von deinem Google-Konto und den aktuellen Bedingungen ab.','Your separate Google API key is stored once with AES-GCM in this Safari profile. Pricing or free quota depends on your Google account and current terms.'):text('Der Schlüssel wird einmalig eingegeben und mit AES-GCM im lokalen Safari-Profil verschlüsselt auf diesem PC gespeichert. OpenAI-Sprachausgabe und Bilderkennung verursachen API-Kosten; ein ChatGPT-Abo deckt sie nicht.','Enter the key once. iPad DPAPI encrypts it on this PC. OpenAI speech and image recognition incur API costs; a ChatGPT subscription does not cover them.')}</p><p>${status.hasKey?text('Ein Schlüssel ist bereits gespeichert. Zum Ersetzen einen neuen eingeben.','A key is already saved. Enter a new key to replace it.'):text('Noch kein Schlüssel gespeichert.','No key is saved.')}</p><label>API-Key <input id="desktopKey" type="password" autocomplete="off" placeholder="sk-…"></label><label ${google?'hidden':''}>${text('Sprachausgabe','Speech output')} <select id="desktopProvider"><option value="tts">${text('iPad-Stimme · kostenlos','iPad voice · free')}</option><option value="openai">${text('OpenAI · API-Kosten','OpenAI · API fees')}</option></select></label><p id="desktopKeyStatus" role="status"></p><div class="controls"><button id="desktopKeySave">${text('Speichern','Save')}</button><button id="desktopKeyForget">${text('Schlüssel löschen','Delete key')}</button><button id="desktopKeyClose">${text('Schließen','Close')}</button></div>`;document.body.append(keyDialog);const find=id=>keyDialog.querySelector('#'+id);find('desktopProvider').value=keepSpeech?(status.provider||'tts'):(status.hasKey?status.provider:'openai');find('desktopKeyForget').disabled=!status.hasKey;
 const close=()=>{find('desktopKey').value='';keyDialog.close();keyDialog.remove();keyDialog=null;host.pickerBusy(false);};find('desktopKeyClose').onclick=close;keyDialog.oncancel=event=>{event.preventDefault();close();};find('desktopKeyForget').onclick=async()=>{await host.forgetKey(kind);close();};find('desktopKeySave').onclick=async()=>{const value=find('desktopKey').value.trim();if(!value&&status.hasKey){if(!google)window.Android.setSpeechProvider(find('desktopProvider').value);close();return;}const saved=await host.saveKey(value,find('desktopProvider').value,kind);if(saved.ok)close();else find('desktopKeyStatus').textContent=saved.error==='encryption_unavailable'?text('Verschlüsselte Speicherung ist auf diesem System nicht verfügbar.','Encrypted storage is unavailable on this system.'):text('Bitte einen gültigen Schlüssel eingeben.','Please enter a valid key.');};keyDialog.showModal();}
function stopCamera(){if(!cameraDialog)return;stream?.getTracks().forEach(track=>track.stop());stream=null;cameraDialog.close();cameraDialog.remove();cameraDialog=null;host.pickerBusy(false);}
async function camera(){if(cameraDialog){host.pickerBusy(false);return;}cameraDialog=document.createElement('dialog');cameraDialog.className='desktop-dialog desktop-camera';cameraDialog.innerHTML=`<h2>${text('Stellung mit der Kamera erfassen','Capture a position with your camera')}</h2><video autoplay playsinline muted></video><p role="status">${text('Kamera wird geöffnet …','Opening camera …')}</p><div class="controls"><button id="desktopCapture" disabled>${text('Foto aufnehmen','Take photo')}</button><button id="desktopCameraClose">${text('Abbrechen','Cancel')}</button></div>`;document.body.append(cameraDialog);const target=cameraDialog,video=target.querySelector('video');target.querySelector('#desktopCameraClose').onclick=stopCamera;target.oncancel=e=>{e.preventDefault();stopCamera();};target.showModal();try{const next=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}},audio:false});if(cameraDialog!==target){next.getTracks().forEach(track=>track.stop());return;}stream=next;video.srcObject=stream;await video.play();target.querySelector('[role=status]').textContent=text('Das ganze Brett möglichst von oben und ohne verdeckte Figuren aufnehmen.','Capture the entire board from above, without obscuring pieces.');target.querySelector('#desktopCapture').disabled=false;target.querySelector('#desktopCapture').onclick=()=>{if(!video.videoWidth)return;const c=document.createElement('canvas'),scale=Math.min(1,2048/Math.max(video.videoWidth,video.videoHeight));c.width=Math.round(video.videoWidth*scale);c.height=Math.round(video.videoHeight*scale);c.getContext('2d').drawImage(video,0,0,c.width,c.height);const data=c.toDataURL('image/jpeg',.94);stopCamera();host.capture(data);};}catch{if(cameraDialog===target)target.querySelector('[role=status]').textContent=text('Kamera nicht verfügbar. In den Safari-Website-Einstellungen Kamera erlauben. Alternativ ein Bild laden.','Kamera unavailable. Allow camera access in Safari website settings, or load an image.');}}
function restoreArchive(data){try{const a=JSON.parse(data);if(a.version!==2||!Array.isArray(a.games)||a.games.length>1000||!a.games.length||!a.games.some(g=>g.id===a.activeId))throw Error();for(const g of a.games){if(typeof g.id!=='string'||!Array.isArray(g.moves)||!Array.isArray(g.chat)||g.moves.length>5000)throw Error();}localStorage.setItem('sprachschach-archive-v2',data);location.reload();}catch{notice('Keine gültige Partiensicherung. Die vorhandenen Daten bleiben erhalten.','Invalid archive backup. Existing data is preserved.');}}
host.onEvent((name,args)=>{if(name==='notice'){notice(...args);return;}if(name==='configureKey'){void configureKey(args[0]||'openai',args[1]===true);return;}if(name==='camera'){void camera();return;}if(name==='stopCamera'){stopCamera();return;}if(name==='stopAudio'){stopAudio();return;}if(name==='playAudio'){void playAudio(...args);return;}if(name==='exportArchive'){host.exportArchive(localStorage.getItem('sprachschach-archive-v2')||'{}');return;}if(name==='restoreArchive'){restoreArchive(args[0]);return;}const allowed=['receiveSpeech','voiceState','voiceEngineChanged','coachAnswer','photoSelected','photoRecognized','receiveSharedContent','engineForegroundChanged'];if(allowed.includes(name)&&typeof window[name]==='function')window[name](...args);});
window.addEventListener('DOMContentLoaded',()=>{labels();const observer=new MutationObserver(labels);for(const id of ['voiceStatus','speechProvider','speechProviderHelp','privacy']){const n=document.getElementById(id);if(n)observer.observe(n,{childList:true,subtree:true,characterData:true});}document.getElementById('language').addEventListener('change',labels);const backup=document.createElement('div');backup.className='controls';const save=document.createElement('button'),load=document.createElement('button');save.textContent=text('Partien und Chat sichern','Back up games and chat');load.textContent=text('Sicherung wiederherstellen','Restore backup');save.onclick=()=>host.showArchiveBackup();load.onclick=()=>host.importArchive();backup.append(save,load);document.querySelector('#archive').closest('.card').append(backup);host.ready();});
window.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.querySelector('#lcdFullscreenPanel:not([hidden])'))window.closeLcdFullscreen?.();});
window.addEventListener('dragover',e=>e.preventDefault());window.addEventListener('drop',async e=>{e.preventDefault();const file=e.dataTransfer.files[0];if(!file)return;try{if(/\.(pgn|fen|txt)$/i.test(file.name)){if(file.size>1024*1024)throw Error();window.receiveSharedContent(String(Date.now()),'text',await file.text());}else if(/\.(png|jpe?g|webp|bmp|gif)$/i.test(file.name)){if(file.size>16*1024*1024)throw Error();const reader=new FileReader();reader.onload=()=>window.receiveSharedContent(String(Date.now()),'image',reader.result);reader.readAsDataURL(file);}else throw Error();}catch{notice('Diese Datei wird nicht unterstützt oder ist zu groß.','This file is unsupported or too large.');}});
