import {model} from './mephisto-models.js';
// Native snapshots are kept in IndexedDB, separate from PGN/chat localStorage.
const database=new Promise((resolve,reject)=>{const r=indexedDB.open('sprachschach-mephisto-web',1);r.onupgradeneeded=()=>r.result.createObjectStore('states',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
async function read(id){const d=await database;return new Promise((resolve,reject)=>{const r=d.transaction('states').objectStore('states').get(id);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function all(){const d=await database;return new Promise((resolve,reject)=>{const r=d.transaction('states').objectStore('states').getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function write(record){const d=await database;return new Promise((resolve,reject)=>{const t=d.transaction('states','readwrite');t.objectStore('states').put(record);t.oncomplete=resolve;t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error);});}
const hash=async bytes=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(b=>b.toString(16).padStart(2,'0')).join('');
const historyId=async(machine,moves)=>'auto:'+machine+':'+await hash(new TextEncoder().encode(moves.join(' ')));
const slot=()=> 'snapshot_'+crypto.randomUUID().replaceAll('-','');
let saves=[],normal=null,raw=null,searchGeneration=0,rawGeneration=0,soundEnabled=true,audioContext;
function tone(edges){if(!soundEnabled||!edges.length)return;try{audioContext??=new (window.AudioContext||window.webkitAudioContext)();if(audioContext.state!=='running')return;const rate=audioContext.sampleRate,length=Math.min(rate,Math.ceil((edges.at(-1)[0]+.03)*rate)),buffer=audioContext.createBuffer(1,length,rate),samples=buffer.getChannelData(0);let index=0,value=0;for(let n=0;n<length;n++){while(index<edges.length&&edges[index][0]<=n/rate)value=edges[index++][1];samples[n]=value*.12;}const source=audioContext.createBufferSource();source.buffer=buffer;source.connect(audioContext.destination);source.start();}catch{}}
document.addEventListener('pointerdown',()=>{if(soundEnabled){audioContext??=new (window.AudioContext||window.webkitAudioContext)();audioContext.resume().catch(()=>{});}},{capture:true});
class Engine{
 constructor(machine,states=[]){this.machine=machine;this.waiters=[];this.files=new Map();this.counter=0;this.failure=null;this.worker=new Worker('mephisto-worker.js');this.worker.onmessage=({data:m})=>{if(globalThis.MEPHISTO_DEBUG&&(m.type==='line'||m.type==='log'||m.type==='error'))console.log(m.type,m.data?.slice(0,160));if(m.type==='line'){this.onLine?.(m.data);for(const w of [...this.waiters])if(m.data.startsWith(w.prefix)){this.waiters.splice(this.waiters.indexOf(w),1);clearTimeout(w.timer);w.resolve(m.data);}}else if(m.type==='file'){const f=this.files.get(m.id);this.files.delete(m.id);f?.resolve(m.bytes);}else if(m.type==='error'||m.type==='log'&&m.data.includes('CHESS BRIDGE ERROR:'))this.fail(Error(m.data));};this.worker.onerror=e=>this.fail(Error(e.message||'Browser emulation failed'));this.worker.postMessage({type:'start',machine,states});}
 fail(error){if(error.message!=='cancelled')console.warn('Mephisto browser engine:',this.machine,error.message);this.failure=error;for(const w of this.waiters){clearTimeout(w.timer);w.reject(error);}this.waiters=[];for(const f of this.files.values())f.reject(error);this.files.clear();this.onError?.(error);}
 until(prefix,timeout=120000){if(this.failure)return Promise.reject(this.failure);return new Promise((resolve,reject)=>{const w={prefix,resolve,reject,timer:null};if(timeout)w.timer=setTimeout(()=>{this.waiters=this.waiters.filter(x=>x!==w);reject(Error('Emulator startup timed out'));},timeout);this.waiters.push(w);});}
 command(...commands){this.worker.postMessage({type:'command',commands});}
 async boot(level){let p=this.until('uciok');this.command('uci');await p;p=this.until('readyok');this.command('setoption name Speed value 0','setoption name Level value '+level,'isready');await p;}
 pause(paused){this.worker.postMessage({type:'pause',paused});}
 file(name){return new Promise((resolve,reject)=>{const id=++this.counter;this.files.set(id,{resolve,reject});this.worker.postMessage({type:'file',machine:this.machine,name,id});});}
 close(){this.worker.terminate();this.fail(Error('cancelled'));}
}
async function checked(record,machine){if(!record||record.machine!==machine||!record.bytes||await hash(record.bytes)!==record.sha256)throw Error('Saved module state missing or damaged');return record;}
const emit=(id,kind,data='')=>globalThis.originalMmviEvent?.(id,kind,data);
const cancel=()=>{searchGeneration++;normal?.close();normal=null;};
async function search(id,json){const generation=++searchGeneration,d=JSON.parse(json);try{
 const compatible=normal&&normal.machine===d.machine&&normal.game===d.game&&normal.level===d.level&&normal.moves.every((m,n)=>d.moves[n]===m)&&d.moves.length>=normal.moves.length;
 if(!compatible){normal?.close();normal=null;let restore=null;if(d.machine==='polgar101'&&d.moves.length>1){restore=await read(await historyId(d.machine,d.moves.slice(0,-1)));if(!restore)throw Error('polgar_history_unavailable');await checked(restore,d.machine);}
  if(generation!==searchGeneration)return;normal=new Engine(d.machine,restore?[{name:restore.slot,bytes:restore.bytes}]:[]);normal.game=d.game;normal.level=d.level;normal.moves=[];normal.onLine=line=>{if(line.startsWith('mephisto_lcd '))globalThis.localMmviDisplay?.(JSON.parse(line.slice(13)));if(line.startsWith('mmvi_display '))globalThis.localMmviDisplay?.(JSON.parse(line.slice(13)));};await normal.boot(d.level);
  if(restore){const p=normal.until('native_restored');normal.command('native restore '+restore.slot+' '+restore.moves.join(' '));await p;normal.moves=restore.moves;}
 }
 if(generation!==searchGeneration)return;const engine=normal;engine.pause(false);let p=engine.until('bestmove ',0);engine.command('setoption name Speed value 100','position startpos'+(d.moves.length?' moves '+d.moves.join(' '):''),'go');const result=await p;const move=result.slice(9).split(' ')[0];if(!/^[a-h][1-8][a-h][1-8][qrbn]?$/.test(move))throw Error('illegal_engine_move');engine.moves=[...d.moves,move];
 const name=slot();p=engine.until('native_saved');engine.command('native checkpoint '+name);await p;const bytes=await engine.file(name);await write({id:await historyId(d.machine,engine.moves),automatic:true,machine:d.machine,slot:name,moves:engine.moves,bytes,sha256:await hash(bytes)});engine.pause(true);
 if(generation===searchGeneration)globalThis.localMmviAnswer?.(id,move,'');
 }catch(e){if(generation===searchGeneration){normal?.close();normal=null;globalThis.localMmviAnswer?.(id,'',e.message==='polgar_history_unavailable'?e.message:'local_emulator_failed');}}}
function stopRaw(){rawGeneration++;const old=raw;raw=null;if(old){old.engine.onError=null;old.engine.close();}}
async function startRaw(id,json){stopRaw();cancel();const generation=rawGeneration,d=JSON.parse(json);try{
 let record=d.restoreSlot?await checked(await read(d.restoreSlot),d.machine):await read('resume:'+d.machine+':'+d.game+':'+d.moves.join(' '));
 if(record)await checked(record,d.machine);if(!record&&d.machine==='polgar101'&&d.moves.length)record=await read(await historyId(d.machine,d.moves));if(record)await checked(record,d.machine);
 if(generation!==rawGeneration)return;const engine=new Engine(d.machine,record?[{name:record.slot,bytes:record.bytes}]:[]);raw={id,engine,data:d,generation,staged:null,state:null,online:false};engine.onError=()=>{if(raw?.engine===engine)emit(id,'error');};engine.onLine=line=>{if(raw?.engine!==engine)return;if(line.startsWith('raw_state ')){raw.state=line.slice(10);if(raw.online)emit(id,'state',raw.state);}if(line.startsWith('raw_tone '))tone(JSON.parse(line.slice(9)));};await engine.boot(d.level);let p=engine.until('raw_ready');engine.command('raw init '+(d.machine==='polgar101'?'':d.moves.join(' ')));await p;if(record){p=engine.until('raw_restored');engine.command('raw restore '+record.slot);await p;}if(raw?.engine===engine){raw.online=true;emit(id,'ready');if(raw.state)emit(id,'state',raw.state);}
 }catch(e){if(generation===rawGeneration)emit(id,'error',e.message);}}
async function saveRaw(){const r=raw;if(!r)return;try{const name=slot(),p=r.engine.until('raw_saved '+name);r.engine.command('raw checkpoint '+name);await p;const bytes=await r.engine.file(name);if(raw!==r)return;r.staged={name,bytes};emit(r.id,'snapshot',name);}catch{if(raw===r)emit(r.id,'save_error');}}
async function commitRaw(name,json){const r=raw;if(!r||r.staged?.name!==name)return;try{const metadata=JSON.parse(json),record={...metadata,id:name,slot:name,format:1,machine:r.data.machine,created:Date.now(),bytes:r.staged.bytes,sha256:await hash(r.staged.bytes)};await write(record);saves=(await all()).filter(x=>!x.automatic&&!x.resume).map(({bytes,...meta})=>meta).sort((a,b)=>b.created-a.created);r.staged=null;emit(r.id,'saved',name);}catch{if(raw===r)emit(r.id,'save_error');}}
async function closeRaw(){const r=raw;if(!r)return;try{const name=slot(),p=r.engine.until('raw_saved '+name);r.engine.command('raw checkpoint '+name);await p;const bytes=await r.engine.file(name);await write({id:'resume:'+r.data.machine+':'+r.data.game+':'+r.data.moves.join(' '),resume:true,machine:r.data.machine,slot:name,bytes,sha256:await hash(bytes)});}catch{}finally{if(raw===r)stopRaw();}}
export function setupMephistoWeb(){
 all().then(records=>saves=records.filter(x=>!x.automatic&&!x.resume).map(({bytes,...meta})=>meta).sort((a,b)=>b.created-a.created)).catch(()=>{});
 Object.assign(window.Android,{hasLocalMmvi:()=>typeof WebAssembly==='object',searchLocalMmvi:search,cancelLocalMmvi:cancel,startOriginalMmvi:startRaw,originalMmviInput:command=>raw?.engine.command('raw '+command),stopOriginalMmvi:closeRaw,originalMmviSound:on=>soundEnabled=!!on,listOriginalMmviSaves:()=>JSON.stringify(saves),saveOriginalMmvi:saveRaw,commitOriginalMmviSave:commitRaw,setOriginalMmviOpen:()=>{},engineForegroundChanged:active=>normal?.pause(!active),playMmviBeep:()=>{if(soundEnabled)new Audio('mmvi/confirmation.wav').play().catch(()=>{});}});
}
