import {Chess} from './core.js';
export function placementToMap(placement){const board={},ranks=String(placement).split('/');if(ranks.length!==8)throw new Error('placement');for(let i=0;i<8;i++){let file=0;for(const c of ranks[i]){if(/[1-8]/.test(c))file+=Number(c);else if(/[prnbqkPRNBQK]/.test(c)){if(file>=8)throw new Error('placement');board['abcdefgh'[file++]+(8-i)]=c;}else throw new Error('placement');}if(file!==8)throw new Error('placement');}return board;}
export function mapToPlacement(board){return Array.from({length:8},(_,i)=>{let row='',empty=0;for(const f of 'abcdefgh'){const p=board[f+(8-i)];if(p){if(empty){row+=empty;empty=0;}row+=p;}else empty++;}return row+(empty||'');}).join('/');}
export function rotatePlacement(board){return Object.fromEntries(Object.entries(board).map(([sq,p])=>['hgfedcba'['abcdefgh'.indexOf(sq[0])]+(9-Number(sq[1])),p]));}
export function recognizedPosition(raw){const result=typeof raw==='string'?JSON.parse(raw):raw;return {board:placementToMap(result.placement),uncertain:(Array.isArray(result.uncertain_squares)?result.uncertain_squares:[]).filter(s=>/^[a-h][1-8]$/.test(s)),notes:String(result.notes||'').slice(0,1500)};}
export function validatePosition(fen,lang='de'){const de=lang==='de',fail=(a,b)=>({ok:false,error:de?a:b});const fields=String(fen).trim().split(/\s+/);if(fields.length!==6||!/^\d+$/.test(fields[4])||!/^\d+$/.test(fields[5])||!Number.isSafeInteger(Number(fields[4]))||!Number.isSafeInteger(Number(fields[5])))return fail('FEN benötigt sechs gültige Angaben.','FEN requires six valid fields.');let g;try{g=new Chess(fen);}catch{return fail('Ungültige Stellung: genau ein König je Farbe, acht Reihen und gültige FEN-Angaben erforderlich.','Invalid position: one king per side, eight ranks and valid FEN fields are required.');}
 const pieces=g.board().flat().filter(Boolean);for(const color of ['w','b']){const own=pieces.filter(p=>p.color===color);if(own.length>16||own.filter(p=>p.type==='p').length>8)return fail('Zu viele Figuren oder Bauern einer Farbe.','Too many pieces or pawns of one color.');}
 const kings=pieces.filter(p=>p.type==='k');if(Math.abs(kings[0].square.charCodeAt(0)-kings[1].square.charCodeAt(0))<=1&&Math.abs(Number(kings[0].square[1])-Number(kings[1].square[1]))<=1)return fail('Die Könige dürfen nicht nebeneinander stehen.','Kings must not be adjacent.');
 const waiting=g.turn()==='w'?'b':'w',king=kings.find(p=>p.color===waiting);if(g.isAttacked(king.square,g.turn()))return fail('Die Seite, die nicht am Zug ist, steht im Schach. Prüfe Figuren und Zugrecht.','The side not to move is in check. Check the pieces and side to move.');
 for(const [right,ks,rs,color]of [['K','e1','h1','w'],['Q','e1','a1','w'],['k','e8','h8','b'],['q','e8','a8','b']])if(fields[2].includes(right)&&(g.get(ks)?.type!=='k'||g.get(ks)?.color!==color||g.get(rs)?.type!=='r'||g.get(rs)?.color!==color))return fail('Rochaderecht passt nicht zu König und Turm auf ihren Ausgangsfeldern.','Castling rights require king and rook on their original squares.');
 if(fields[3]!=='-'){const ep=fields[3],pawn=ep[0]+(g.turn()==='w'?'5':'4'),origin=ep[0]+(g.turn()==='w'?'7':'2');if(g.get(ep)||g.get(origin)||g.get(pawn)?.type!=='p'||g.get(pawn)?.color!==waiting||Number(fields[4])!==0)return fail('En-passant-Feld passt nicht zu einem gerade erfolgten Bauerndoppelschritt.','En passant target does not match a just-played double pawn move.');}
 return {ok:true,fen:g.fen(),game:g};
}
