import {setupMultiPv} from './multipv.js';
import {prepareTabletLayout} from './tablet-layout.js';
// Home-screen installation and offline readiness are reported separately.
window.addEventListener('DOMContentLoaded',()=>{
 prepareTabletLayout();setupMultiPv();
 const card=document.createElement('section');card.className='card pwa-card';card.innerHTML='<small>ANDROID / IPAD · WEB-APP · 1.1.6</small><p>Safari: Teilen → Zum Home-Bildschirm. Zum ersten Sprachstart „Zug sprechen“ antippen und Mikrofon freigeben. Die App hört nur im Vordergrund zu.</p><p id="offlineStatus" role="status">Offline-Dateien werden vorbereitet …</p><button id="pwaReload" hidden>Neue Version öffnen</button>';
 document.querySelector('main').append(card);const status=document.getElementById('offlineStatus'),hadController=!!navigator.serviceWorker?.controller;document.getElementById('pwaReload').onclick=()=>location.reload();
 document.getElementById('mic').addEventListener('click',()=>{window.pwaSpeechStarted=true;},{capture:true});document.getElementById('handsFree').addEventListener('change',e=>{if(e.target.checked)window.pwaSpeechStarted=true;},{capture:true});
 if(!('serviceWorker' in navigator)||!window.isSecureContext){status.textContent='Offline-Nutzung und Home-Bildschirm benötigen eine HTTPS-Adresse. Diese Dateien nicht direkt aus der Dateien-App öffnen.';return;}
 navigator.serviceWorker.addEventListener('controllerchange',()=>{if(hadController){window.pwaUpdateReady=true;status.textContent='Neue Version bereit: Bitte neu laden, um alle Änderungen zu verwenden.';document.getElementById('pwaReload').hidden=false;}});
 navigator.serviceWorker.addEventListener('message',e=>{if(window.pwaUpdateReady)return;if(e.data?.type==='offline-progress')status.textContent=`Offline-Dateien: ${e.data.done} von ${e.data.total}. Safari geöffnet lassen …`;if(e.data?.type==='offline-ready')status.textContent='Offline bereit: Stockfish und Schachfunktionen verfügbar. KI und ggf. Spracherkennung benötigen Internet.';});
 navigator.serviceWorker.register('./sw.js',{scope:'./'}).then(async registration=>{const worker=registration.installing;if(worker)worker.addEventListener('statechange',()=>{if(worker.state==='redundant')status.textContent='Offline-Download fehlgeschlagen. Internet/Speicher prüfen und die Seite erneut laden.';});await navigator.serviceWorker.ready;navigator.serviceWorker.controller?.postMessage({type:'offline-status'});registration.active?.postMessage({type:'offline-status'});}).catch(()=>{status.textContent='Offline-Einrichtung fehlgeschlagen. HTTPS, Speicher und Internetverbindung prüfen.';});
});
