import {Chess} from './core.js';
import {outcomeText} from './outcome.js';
export const archiveKey='sprachschach-archive-v2';
export const moveObject=m=>({from:m.from,to:m.to,...(m.promotion?{promotion:m.promotion}:{})});
export const uci=m=>m.from+m.to+(m.promotion||'');
export function newSession(human='w') {const now=new Date().toISOString();return {id:globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`,created:now,updated:now,human,moves:[],chat:[],review:null};}
export function restoreGame(session){const g=new Chess(session.startFen);if(session.pgn){g.loadPgn(session.pgn);return g;}for(const m of session.moves)g.move(m);return g;}
export function migrateLegacy(old){const s=newSession(old.human==='b'?'b':'w');const g=new Chess();for(const [index,move] of (old.moves||[]).entries()){const m=g.move(move);s.moves.push(moveObject(m));const original=old.records?.[index];s.chat.push({kind:'move',ply:index+1,color:m.color,san:m.san,move:moveObject(m),text:original?.text||'',lang:old.lang==='en'?'en':'de',at:s.created});}return s;}
export function terminalEvaluation(g){if(g.isCheckmate())return {cp:g.turn()==='w'?-10000:10000,mate:g.turn()==='w'?-1:1,terminal:true};if(g.isDraw())return {cp:0,terminal:true};return null;}
export function parseEvaluation(line,turn){if(!line.startsWith('info ')||/\b(?:lowerbound|upperbound)\b/.test(line))return null;const m=line.match(/\bscore (cp|mate) (-?\d+)/);if(!m)return null;const sign=turn==='w'?1:-1,v=Number(m[2]),pv=[];for(const move of (line.match(/\bpv (.+)$/)?.[1]||'').trim().split(/\s+/)){if(!/^[a-h][1-8][a-h][1-8][qrbn]?$/.test(move)||pv.length>=32)break;pv.push(move);}const time=line.match(/\btime (\d+)/),nodes=line.match(/\bnodes (\d+)/);return {cp:m[1]==='mate'?(v>=0?10000:-10000)*sign:v*sign,...(m[1]==='mate'?{mate:v*sign}:{}),depth:Number(line.match(/\bdepth (\d+)/)?.[1]||0),best:pv[0]||null,pv,...(time?{timeMs:Number(time[1])}:{}),...(nodes?{nodes:Number(nodes[1])}:{})};}
export function assessMoves(moves,evaluations,startColor='w'){return moves.map((m,i)=>{const before=evaluations[i],after=evaluations[i+1];if(!before||!after)return null;const color=i%2===0?startColor:(startColor==='w'?'b':'w');const loss=Math.max(0,(before.cp-after.cp)*(color==='w'?1:-1));return {ply:i+1,color,move:m,loss,best:before.best===uci(m),before,after};}).filter(Boolean);}
export function resultText(g,lang){const de=lang==='de';if(g.isCheckmate())return g.turn()==='w'?(de?'Schwarz gewinnt durch Schachmatt.':'Black wins by checkmate.'):(de?'Weiß gewinnt durch Schachmatt.':'White wins by checkmate.');if(g.isStalemate())return de?'Remis durch Patt.':'Draw by stalemate.';if(g.isThreefoldRepetition())return de?'Remis durch Stellungswiederholung.':'Draw by repetition.';if(g.isInsufficientMaterial())return de?'Remis wegen unzureichenden Materials.':'Draw by insufficient material.';if(g.isDraw())return de?'Die Partie endet remis.':'The game ends in a draw.';return de?'Die Partie läuft noch.':'The game is still in progress.';}
export function buildSummary(session,lang){return buildSummaryParts(session,lang).map(part=>part.text).join("\n\n");}
export function buildSummaryParts(session,lang){const de=lang==='de',g=restoreGame(session),played=g.history({verbose:true}),review=session.review;
 const importedResult=!g.isGameOver()&&g.fen()===session.sourceFinalFen&&played.map(uci).join(' ')===session.sourceUci&&['1-0','0-1','1/2-1/2'].includes(session.sourceResult);const importedOutcome=session.sourceResult==='1-0'?(de?'Weiß gewinnt.':'White wins.'):session.sourceResult==='0-1'?(de?'Schwarz gewinnt.':'Black wins.'):(de?'Remis.':'Draw.');
 const lines=[de?'Partiezusammenfassung':'Game summary',importedResult?(de?'Ergebnis der importierten Partie: ':'Imported game result: ')+importedOutcome:outcomeText(session,g,lang)||resultText(g,lang),de?`${played.length} Halbzüge (${Math.ceil(played.length/2)} Zugpaare).`:`${played.length} half-moves (${Math.ceil(played.length/2)} move pairs).`];
 if(!review||review.status!=='complete'){lines.push(de?'Stockfish-Analyse ist noch nicht abgeschlossen. Gute Züge und Patzer werden erst nach der Analyse bewertet.':'Stockfish analysis is not complete. Good moves and blunders will be assessed after analysis.');return summaryPartsFromText(lines.join('\n\n'),session.moves,session.human,lang,session.startFen);}
 const assessed=assessMoves(session.moves,review.evaluations,new Chess(session.startFen).turn());const label=m=>`${played[m.ply-1].before.split(' ')[5]}${m.color==='w'?'.':'...'} ${played[m.ply-1].san}`;const side=color=>de?(color==='w'?'Weiß':'Schwarz'):(color==='w'?'White':'Black');
 lines.push(de?'Gesamteinschätzung':'Overall assessment');for(const color of ['w','b']){const own=assessed.filter(m=>m.color===color),blunders=own.filter(m=>m.loss>=200).length,errors=own.filter(m=>m.loss>=80&&m.loss<200).length,avg=own.length?own.reduce((a,m)=>a+Math.min(m.loss,1000),0)/own.length/100:0;lines.push(de?`${side(color)}: ${blunders} Patzer und ${errors} Fehler; durchschnittlicher Bewertungsverlust etwa ${avg.toFixed(2)} Bauerneinheiten (Mattwerte begrenzt).`:`${side(color)}: ${blunders} blunders and ${errors} mistakes; average evaluation loss about ${avg.toFixed(2)} pawn units (mate scores capped).`);}
 const good=assessed.filter(m=>m.best&&m.loss<=35).sort((a,b)=>{const mate=x=>x.after.mate!==undefined&&x.after.cp*(x.color==='w'?1:-1)>0?1:0;return mate(b)-mate(a)||b.ply-a.ply;}).slice(0,4);
 lines.push(de?'Gute Züge':'Good moves');if(!good.length)lines.push(de?'Bei dieser kurzen Analyse wurde kein Zug zuverlässig als besonders gut hervorgehoben.':'This short analysis did not reliably identify a standout good move.');for(const m of good){const mate=m.after.mate!==undefined&&m.after.cp*(m.color==='w'?1:-1)>0;lines.push(de?`${side(m.color)} ${label(m)}: entspricht Stockfishs bevorzugtem Zug${mate?' und erhält einen erzwungenen Mattangriff':' und hält die Stellungsbewertung weitgehend'}.`:`${side(m.color)} ${label(m)}: matches Stockfish’s preferred move${mate?' and maintains a forced mating attack':' and largely preserves the position’s evaluation'}.`);}
 const bad=assessed.filter(m=>m.loss>=200).sort((a,b)=>b.loss-a.loss).slice(0,4);lines.push(de?'Patzer und Wendepunkte':'Blunders and turning points');if(!bad.length)lines.push(de?'Kein Patzer mit mindestens zwei Bauerneinheiten Bewertungsverlust erkannt.':'No blunder with an evaluation loss of at least two pawn units detected.');for(const m of bad){const mate=m.after.mate!==undefined&&m.after.cp*(m.color==='w'?1:-1)<0;const missed=m.before.mate!==undefined&&m.before.cp*(m.color==='w'?1:-1)>0&&! (m.after.cp*(m.color==='w'?1:-1)>=10000);lines.push(de?`${side(m.color)} ${label(m)}: ${mate?'ermöglicht einen erzwungenen Mattangriff des Gegners':missed?'vergibt einen erzwungenen Mattangriff':`Bewertungsverlust etwa ${(m.loss/100).toFixed(2)} Bauerneinheiten`}.`:`${side(m.color)} ${label(m)}: ${mate?'allows the opponent a forced mating attack':missed?'misses a forced mating attack':`evaluation loss about ${(m.loss/100).toFixed(2)} pawn units`}.`);}
 lines.push(de?'Grundlage: kurze lokale Stockfish-17.1-Analyse (12.000 Suchknoten pro Stellung), keine endgültige Bewertung. Fehler ab 0,8; Patzer ab 2,0 Bauerneinheiten. Gute Züge stimmen mit Stockfishs Hauptvariante überein.':'Based on a short local Stockfish 17.1 analysis (12,000 search nodes per position), not a definitive assessment. Mistakes start at 0.8 and blunders at 2.0 pawn units. Good moves match Stockfish’s principal variation.');return summaryPartsFromText(lines.join('\n\n'),session.moves,session.human,lang,session.startFen);
}

// Keep each position with its explanation so later takebacks cannot alter the diagram.
export function summaryPartsFromText(text,moves,orientation='w',lang='de',startFen=undefined){
 const parts=text.split('\n\n').map(text=>({text}));
 const g=new Chess(startFen),positions=[g.fen()],played=[];
 try{for(const m of moves){played.push(g.move(m));positions.push(g.fen());}}catch{return parts;}
 function snapshot(ply){if(ply===0)return {ply:0,fen:positions[0],move:null,initial:true,orientation:orientation==='b'?'b':'w'};const m=played[ply-1];if(!m)return null;return {ply,fen:positions[ply],beforeFen:positions[ply-1],move:moveObject(m),san:m.san,number:Number(m.before.split(' ')[5]),color:m.color,orientation:orientation==='b'?'b':'w'};}
 for(const [index,part] of parts.entries()){
  const match=part.text.match(/^(Weiß|Schwarz|White|Black) (\d+)(\.\.\.|\.) (\S+):/);
  if(match){const color=['Weiß','White'].includes(match[1])?'w':'b';const ply=played.findIndex(m=>m.color===color&&Number(m.before.split(' ')[5])===Number(match[2]))+1;if(played[ply-1]?.san===match[4]&&played[ply-1]?.color===color)part.position=snapshot(ply);}
  else if(index===1&&g.isGameOver())part.position=snapshot(played.length);
 }
 return parts;
}
export function hydrateSummaryParts(session){
 const replay=new Chess(session.startFen);let valid=true;
 for(const entry of session.chat){
  if(entry.kind==='move'&&entry.move){if(!Number.isInteger(entry.ply)||entry.ply<1){valid=false;continue;}try{while(replay.history().length>=entry.ply)replay.undo();if(replay.history().length!==entry.ply-1)valid=false;else{replay.move(entry.move);valid=true;}}catch{valid=false;}}
  if(entry.kind==='summary'&&!entry.parts&&valid)entry.parts=summaryPartsFromText(entry.text,replay.history({verbose:true}).map(moveObject),session.human,entry.lang||'de',session.startFen);
 }
}
