import {parseTransfer} from './transfer.js';
import {renderSummary} from './summary-view.js';
export function createTextImport({language,onOpen,onClose,onImport}){const dialog=document.createElement('dialog');dialog.id='textImport';dialog.className='position-import';document.body.append(dialog);const $=id=>dialog.querySelector('#'+id),say=(a,b)=>language()==='de'?a:b;let parsed=null;
 function preview(){parsed=null;$('acceptTextImport').disabled=true;$('transferGames').replaceChildren();$('transferPreview').replaceChildren();try{parsed=parseTransfer($('transferText').value,language());parsed.games.forEach((g,i)=>{const option=document.createElement('option');option.value=i;option.textContent=parsed.kind==='fen'?say('FEN-Stellung','FEN position'):`${i+1}. ${g.headers.White||'?'} – ${g.headers.Black||'?'} · ${g.moves.length} ${say('Halbzüge','half-moves')}`;$('transferGames').append(option);});$('transferStatus').textContent=say('Geprüft. Eine Partie wählen und zum Analysieren übernehmen.','Validated. Choose a game and import it for analysis.');$('acceptTextImport').disabled=false;draw();}catch(e){$('transferStatus').textContent=e.message;}}
 function draw(){if(!parsed)return;const g=parsed.games[Number($('transferGames').value)||0];const position={ply:0,fen:g.finalFen,initial:true,title:parsed.kind==='fen'?say('Geteilte Stellung','Shared position'):say('Letzte Stellung der Partie','Final position of game'),orientation:'w',move:null};renderSummary($('transferPreview'),[{text:parsed.kind==='fen'?say('Geteilte Stellung','Shared position'):say('Letzte Stellung der Partie','Final position of game'),position}],language());}
 function close(){dialog.close();dialog.replaceChildren();parsed=null;onClose();}
 function accept(){if(!parsed)return;if(onImport(parsed.games[Number($('transferGames').value)||0])===false){$('transferStatus').textContent=say('Speichern fehlgeschlagen. Vorhandene Partien bleiben erhalten.','Saving failed. Existing games are retained.');return;}close();}
 function open(text=''){if(dialog.open)close();onOpen();dialog.innerHTML=`<header class="position-header"><h2>${say('PGN / FEN importieren','Import PGN / FEN')}</h2></header><div class="position-scroll"><p>${say('PGN-Partie oder FEN-Stellung einfügen, eine Datei wählen oder aus einer anderen App mit „Teilen → SprachSchach“ senden.','Paste a PGN game or FEN position, choose a file, or use “Share → SprachSchach” from another app.')}</p><button id="chooseChessFile">${say('PGN-/FEN-Datei wählen','Choose PGN/FEN file')}</button><textarea id="transferText" rows="7" aria-label="PGN / FEN"></textarea><button id="previewTransfer">${say('Import prüfen','Check import')}</button><p id="transferStatus" role="status"></p><label>${say('Partie / Stellung','Game / position')}<select id="transferGames"></select></label><div id="transferPreview"></div><p>${say('Die vollständige Hauptvariante bleibt gespeichert. Frühere Stellungen können mit der Zugnavigation angesehen und von Stockfish bewertet werden. Der Import und die lokale Analyse benötigen keinen API-Schlüssel.','The complete main line is retained. Browse earlier positions and evaluate them with Stockfish. Import and local analysis do not require an API key.')}</p></div><footer class="position-actions"><button id="acceptTextImport" disabled>${say('Zum Analysieren übernehmen','Import for analysis')}</button><button id="cancelTextImport">${say('Abbrechen','Cancel')}</button></footer>`;$('transferText').value=text;$('transferText').oninput=()=>{parsed=null;$('acceptTextImport').disabled=true;$('transferStatus').textContent=say('Eingabe geändert. Bitte Import erneut prüfen.','Input changed. Check the import again.');};$('previewTransfer').onclick=preview;$('transferGames').onchange=draw;$('chooseChessFile').onclick=()=>{if(window.Android?.pickChessDocument)Android.pickChessDocument();else $('transferStatus').textContent=say('Dateiauswahl ist in der Android-App verfügbar.','File selection is available in the Android app.');};$('acceptTextImport').onclick=accept;$('cancelTextImport').onclick=close;dialog.oncancel=e=>{e.preventDefault();close();};dialog.showModal();if(text)preview();}
 function voice(text){if(!dialog.open)return false;const s=text.toLowerCase().trim().replace(/[.!?]+$/,'').replace(/^(?:bitte |please )/,'');if(/^(?:import prüfen|check import)$/.test(s))preview();else if(/^(?:partie übernehmen|stellung übernehmen|import game|import position|accept import)$/.test(s))accept();else if(/^(?:abbrechen|cancel)$/.test(s))close();else if(/^(?:datei wählen|choose file)$/.test(s))$('chooseChessFile').click();return true;}
 return {open,close,isOpen:()=>dialog.open,voice};}
