import {Chess} from './core.js';
import {parseVariations} from './variations.js';
import {validatePosition} from './position.js';
import {moveObject,uci,newSession} from './review.js';
export function splitPgnGames(text){const parts=[];let start=0,brace=0,variation=0,quote=false,tag=false,lineComment=false,seenMoves=false,hasTag=false;for(let i=0;i<text.length;i++){const c=text[i];if(lineComment){if(c==='\n')lineComment=false;continue;}if(brace){if(c==='}')brace--;else if(c==='{')brace++;continue;}if(tag){if(c==='"'&&text[i-1]!=='\\')quote=!quote;if(c===']'&&!quote)tag=false;continue;}if(c==='{'){brace++;continue;}if(c===';'){lineComment=true;continue;}if(c==='('){if(++variation>30)throw new Error('PGN variants too deep');continue;}if(c===')'){if(variation)variation--;continue;}if(variation)continue;if(c==='['){if(seenMoves){const chunk=text.slice(start,i).trim();if(chunk)parts.push(chunk);start=i;seenMoves=false;}tag=true;hasTag=true;continue;}const result=text.slice(i).match(/^(1\/2-1\/2|1-0|0-1|\*)(?=\s|$)/);if(result&&(i===0||/\s/.test(text[i-1]))){parts.push(text.slice(start,i+result[0].length).trim());start=i+result[0].length;i=start-1;seenMoves=false;hasTag=false;}else if(!/\s/.test(c))seenMoves=true;if(parts.length>100)throw new Error('Too many games');}const rest=text.slice(start).trim();if(rest){if(!seenMoves&&!hasTag&&parts.length)parts[parts.length-1]+='\n'+rest;else parts.push(rest);}if(brace||variation||tag)throw new Error('Incomplete PGN');return parts;}
const fenPattern=/((?:[prnbqkPRNBQK1-8]+\/){7}[prnbqkPRNBQK1-8]+)\s+([wb])\s+([KQkq]+|-)\s+([a-h][36]|-)\s+(\d+)\s+(\d+)/;
export function parseTransfer(raw,lang='de'){const say=(a,b)=>lang==='de'?a:b;let text=String(raw||'').replace(/^\uFEFF/,'').trim();if(text.length>262144)throw new Error(say('Die Datei ist zu groß (maximal 256.000 Zeichen).','The file is too large (maximum 256,000 characters).'));if(!text)throw new Error(say('Bitte PGN oder FEN einfügen bzw. eine Datei wählen.','Paste PGN or FEN, or choose a file.'));
 if(/^https?:\/\/\S+$/.test(text)){try{const url=new URL(text),embedded=url.searchParams.get('fen')||url.searchParams.get('FEN');if(embedded)text=embedded;else throw new Error();}catch{throw new Error(say('Es wurde nur ein Weblink geteilt. Bitte aus der anderen App PGN, FEN oder ein Bild teilen.','Only a web link was shared. Share PGN, FEN or an image from the other app.'));}}
 const tagged=/\[[A-Za-z0-9_]+\s+"/.test(text),hasMoves=/(?:^|\n)\s*\d+\./.test(text);if(!tagged&&!hasMoves){const match=text.match(fenPattern);if(match){const fen=match.slice(1).join(' '),validation=validatePosition(fen,lang);if(!validation.ok)throw new Error(validation.error);return {kind:'fen',games:[{startFen:validation.fen,moves:[],headers:{},result:'*',finalFen:validation.fen,sourceUci:''}]};}}
 const firstTag=text.search(/\[[A-Za-z0-9_]+\s+"/);if(firstTag>0&&!/(?:^|\s)\d+\./.test(text.slice(0,firstTag)))text=text.slice(firstTag);if(!tagged&&!/(?:^|\s)\d+\.(?:\.\.)?\s*\S/.test(text))throw new Error(say('Kein PGN und keine vollständige FEN erkannt. Bitte PGN, FEN oder ein Bild teilen.','No PGN or complete FEN found. Share PGN, FEN or an image.'));
 let chunks;try{chunks=splitPgnGames(text);}catch{throw new Error(say('Die PGN-Datei ist unvollständig oder enthält zu viele Partien/Varianten.','The PGN file is incomplete or contains too many games/variations.'));}let total=0;const games=chunks.map((pgn,index)=>{const g=new Chess();try{g.loadPgn(pgn);}catch{throw new Error(say(`Partie ${index+1}: ungültige PGN oder illegaler Zug.`,`Game ${index+1}: invalid PGN or illegal move.`));}const played=g.history({verbose:true});total+=played.length;if(played.length>2000||total>5000)throw new Error(say('Zu viele Züge in dieser PGN-Datei. Bitte einzelne Partien teilen.','Too many moves in this PGN file. Share individual games.'));const headers=g.getHeaders(),startFen=played[0]?.before||headers.FEN||g.fen(),validation=validatePosition(startFen,lang);if(!validation.ok)throw new Error(say(`Partie ${index+1}: `,`Game ${index+1}: `)+validation.error);let variations;try{variations=parseVariations(pgn,validation.fen,played.map(moveObject));}catch{throw new Error(say(`Partie ${index+1}: ungültige Variante.`,`Game ${index+1}: invalid variation.`));}return {variations,startFen:validation.fen,moves:played.map(moveObject),headers:Object.fromEntries(Object.entries(headers).filter(([k])=>!['FEN','SetUp'].includes(k))),result:['1-0','0-1','1/2-1/2','*'].includes(headers.Result)?headers.Result:'*',finalFen:g.fen(),sourceUci:played.map(uci).join(' '),comments:g.getComments()};});if(!games.length)throw new Error(say('Keine Partie gefunden.','No game found.'));return {kind:'pgn',games};}
export function transferredSession(parsed,human='w'){const s=newSession(human);s.analysis=true;s.startFen=parsed.startFen;s.moves=parsed.moves;s.variations=parsed.variations||[];s.sourceHeaders=parsed.headers;s.sourceResult=parsed.result;s.sourceFinalFen=parsed.finalFen;s.sourceUci=parsed.sourceUci;s.sourceComments=parsed.comments||[];s.imported=true;return s;}
export function gameAtPly(session,ply){const g=new Chess(session.startFen);for(const m of session.moves.slice(0,Math.max(0,Math.min(session.moves.length,ply))))g.move(m);return g;}
