import {Chess} from './core.js';
const obj=m=>({from:m.from,to:m.to,...(m.promotion?{promotion:m.promotion}:{})});
export function variationMoves(session,id=null,seen=new Set()){if(!id)return session.moves||[];if(seen.has(id)||seen.size>=30)throw Error('Variation cycle or depth');seen.add(id);const v=(session.variations||[]).find(v=>v.id===id);if(!v)throw Error('Missing variation');const parent=variationMoves(session,v.parentId||null,seen);if(!Number.isInteger(v.basePly)||v.basePly<0||v.basePly>=parent.length)throw Error('Invalid variation fork');return [...parent.slice(0,v.basePly),...v.moves];}
export function variationGame(session,id=null){const g=new Chess(session.startFen);for(const m of variationMoves(session,id))g.move(m);return g;}
export function createVariation(session,parentId,ply){const line=variationMoves(session,parentId);if(!Number.isInteger(ply)||ply<0||ply>=line.length)throw Error('Go back one half-move before creating a variation');let parent=(session.variations||[]).find(v=>v.id===parentId);while(parent&&ply<=parent.basePly){parentId=parent.parentId||null;parent=(session.variations||[]).find(v=>v.id===parentId);}const vars=session.variations??=[];if(vars.length>=200)throw Error('Too many variations');const v={id:globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`,parentId:parentId||null,basePly:ply,moves:[],name:'Variante '+(vars.length+1)};vars.push(v);variationMoves(session,v.id);return v;}
export function deleteVariation(session,id){const ids=new Set([id]);let changed=true;while(changed){changed=false;for(const v of session.variations||[])if(ids.has(v.parentId)&&!ids.has(v.id)){ids.add(v.id);changed=true;}}session.variations=(session.variations||[]).filter(v=>!ids.has(v.id));return ids;}
export function variationsPgn(session,main){const vars=session.variations||[];if(vars.length>200||new Set(vars.map(v=>v.id)).size!==vars.length)throw Error('Invalid variation collection');for(const v of vars)variationGame(session,v.id);const comments=new Map((session.sourceComments||[]).map(c=>[c.fen,c.comment]));const safe=text=>String(text).replace(/[{}]/g,'').replace(/[\r\n]/g,' ');function line(id=null,depth=0){if(depth>=30)throw Error('Variation depth');const v=vars.find(v=>v.id===id),moves=id?variationMoves(session,id):main.history({verbose:true}).map(obj),g=new Chess(session.startFen),words=[];const intro=id?(v.comments||[]).filter(c=>c.ply===v.basePly).map(c=>c.text).join(' '):comments.get(g.fen());if(intro)words.push('{'+safe(intro)+'}');for(let i=0;i<moves.length;i++){const m=g.move(moves[i]);if(i<(v?.basePly||0))continue;words.push(`${m.before.split(' ')[5]}${m.color==='w'?'.':'...'} ${m.san}`);const comment=id?(v.comments||[]).filter(c=>c.ply===i+1).map(c=>c.text).join(' '):comments.get(g.fen());if(comment)words.push('{'+safe(comment)+'}');for(const child of vars.filter(c=>(c.parentId||null)===id&&c.basePly===i&&c.moves.length))words.push('('+line(child.id,depth+1)+')');}return words.join(' ');}return line();}
export function parseVariations(pgn,startFen,expectedMoves){const text=pgn.replace(/\[[A-Za-z0-9_]+\s+"(?:\\.|[^"\\])*"\s*\]/g,'');const tokens=text.match(/\{[^}]*\}|;[^\r\n]*|\(|\)|\$\d+|\d+\.(?:\.\.)?|[^\s(){};]+/g)||[],vars=[],stack=[];let ctx={id:null,g:new Chess(startFen)};for(let token of tokens){if(token==='('){if(!ctx.g.history().length||stack.length>=30||vars.length>=200)throw Error('Invalid variation');const basePly=ctx.g.history().length-1,v={id:'import-v'+(vars.length+1),parentId:ctx.id,basePly,moves:[],name:'Variante '+(vars.length+1),comments:[]};vars.push(v);const g=new Chess(startFen);for(const m of ctx.g.history({verbose:true}).slice(0,basePly))g.move(obj(m));stack.push(ctx);ctx={id:v.id,g,v};continue;}if(token===')'){if(!stack.length)throw Error('Unbalanced variation');ctx=stack.pop();continue;}if(token.startsWith('{')||token.startsWith(';')){if(ctx.v)ctx.v.comments.push({ply:ctx.g.history().length,text:token.startsWith('{')?token.slice(1,-1):token.slice(1)});continue;}if(/^\d+\./.test(token)||/^\$\d+$/.test(token)||/^(?:1-0|0-1|1\/2-1\/2|\*|e\.p\.|[!?]+)$/.test(token))continue;const m=ctx.g.move(token);if(ctx.v)ctx.v.moves.push(obj(m));}if(stack.length)throw Error('Unbalanced variation');if(JSON.stringify(ctx.g.history({verbose:true}).map(obj))!==JSON.stringify(expectedMoves))throw Error('PGN main line mismatch');const s={startFen,moves:expectedMoves,variations:vars};for(const v of vars)variationGame(s,v.id);return vars;}

// Resolve a move at the displayed position without discarding an existing future.
export function moveContinuation(session,id,ply,move){
 const line=variationMoves(session,id),key=m=>m.from+m.to+(m.promotion||'');
 if(!Number.isInteger(ply)||ply<0||ply>line.length)throw Error('Invalid move position');
 const position=new Chess(session.startFen);for(const m of line.slice(0,ply))position.move(m);position.move(move);
 if(ply===line.length)return {kind:'append',id:id||null};
 if(key(line[ply])===key(move))return {kind:'follow',id:id||null,ply:ply+1};
 let parent=(session.variations||[]).find(v=>v.id===id);
 while(parent&&ply<=parent.basePly){id=parent.parentId||null;parent=(session.variations||[]).find(v=>v.id===id);}
 const parentLine=variationMoves(session,id);
 if(key(parentLine[ply])===key(move))return {kind:'follow',id:id||null,ply:ply+1};
 const existing=(session.variations||[]).find(v=>(v.parentId||null)===(id||null)&&v.basePly===ply&&v.moves.length&&key(v.moves[0])===key(move));
 if(existing)return {kind:'follow',id:existing.id,ply:ply+1};
 return {kind:'fork',id:createVariation(session,id,ply).id};
}

export function positionLineId(session,id,ply){let v=(session.variations||[]).find(v=>v.id===id);while(v&&ply<=v.basePly){id=v.parentId||null;v=(session.variations||[]).find(v=>v.id===id);}return id||null;}
